### ISSUE TITLE
Provide themes without autoprefixer applied?

### ISSUE THREAD

**Issue by mjy9088** [PrismJS/prism-themes#160]
## Problem

I'm using theme css files in postcss with autoprefixer enabled, like following:

```postcss
body:not(.dark) {
  @nested-import "../../submodules/prism-themes/themes/prism-one-light.css";
}

body.dark {
  @nested-import "../../submodules/prism-themes/themes/prism-one-dark.css";
}
```

It produces duplicate selector like following:

```css
  code[class*="language-"]::-moz-selection,
  code[class*="language-"] ::-moz-selection,
  pre[class*="language-"] ::-moz-selection {
    background: #e5e5e6;
    color: inherit;
  }
  code[class*="language-"]::-moz-selection,
  code[class*="language-"] ::-moz-selection,
  pre[class*="language-"] ::-moz-selection {
    background: #e5e5e6;
    color: inherit;
  }
  code[class*="language-"]::selection,
  code[class*="language-"] ::selection,
  pre[class*="language-"] ::selection {
    background: #e5e5e6;
    color: inherit;
  }
```

## Current workaround

Edit file: remove prefixed selectors manually

## Possible solutions?

- provide unprefixed version too (like `themes/prism-one-dark-unprefixed.css`)
