### ISSUE TITLE
Line number styles

### ISSUE THREAD

**Issue by tobiju** [PrismJS/prism-themes#51]
What do you think about the line number styles. Would be really nice if you could integrate them into your styles.

**Comment by thehappybug** [comment]
I think the themes should add styles for the standard plug-ins provided by prismjs library. I am currently stuck with a non-functional line number and line highlighter plugin.

**Comment by atelierbram** [comment]
I am willing to work on this, but before doing that I would like to know what the maintainers think about this. Also how to integrate these styles for line-numbers and line-highlight into the themes if this would be encouraged. My suggestion would be to only include snippets of property/value pairs of declarations that actually have color-values, like:

```css
/* overrides color-values for the Line Numbers plugin
 * https://github.com/PrismJS/prism/blob/gh-pages/plugins/line-numbers/prism-line-numbers.css 
 */ 
.line-numbers .line-numbers-rows { 
  border-right-color: #2c2937;
}
.line-numbers-rows > span:before { 
  color: #3c3949;
}
/* overrides color-values for the Line Highlight plugin
 * https://github.com/PrismJS/prism/blob/gh-pages/plugins/line-highlight/prism-line-highlight.css
 */ 
.line-highlight { 
  background: rgba(179,117,55,0.2);
  background:linear-gradient(to right, rgba(179,117,55,0.2) 70%, rgba(179,117,55,0));
}  
``` 

The advantage of doing it like this (_with clear links in the comments_), instead of including all of the plugin's CSS would be to keep the file-sizes small for people who don't use the line-numbers or line-highlight plugin, and also easy to remove if so decided.
